# Generated by Django 3.0.2 on 2020-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20200223_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tabtime',
            field=models.DateTimeField(verbose_name='记录时间'),
        ),
    ]
