# Generated by Django 3.0.2 on 2020-03-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20200302_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tabtime',
            field=models.DateField(verbose_name='记录时间'),
        ),
    ]
