# Generated by Django 3.0.2 on 2020-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20200303_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tabfile',
            field=models.FileField(default='', upload_to='../media/records/', verbose_name='上传记录'),
        ),
    ]
