# Generated by Django 3.0.4 on 2020-04-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20200312_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhiliangshouce',
            name='xuhao',
            field=models.CharField(default=11, max_length=100, verbose_name='编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zhiliangshouce',
            name='shouceauthor',
            field=models.CharField(choices=[('admin', 'admin'), ('xiaoma', 'xiaoma'), ('xiaoqiang', 'xiaoqiang'), ('xiaoxiao', 'xiaoxiao')], max_length=20, verbose_name='编制者'),
        ),
    ]
