# Generated by Django 3.0.2 on 2020-02-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productno', models.IntegerField(verbose_name='商品序列码')),
                ('productname', models.CharField(max_length=50, verbose_name='商品名称')),
                ('productvalue', models.FloatField(verbose_name='商品单价')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('total_value', models.FloatField(verbose_name='商品总价')),
            ],
            options={
                'verbose_name_plural': '销售清单',
            },
        ),
    ]
