# Generated by Django 3.0.2 on 2020-02-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salelist',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='salelist',
            name='productvalue',
        ),
        migrations.RemoveField(
            model_name='salelist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salelist',
            name='total_value',
        ),
    ]
