# Generated by Django 3.0.2 on 2020-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200227_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelist',
            name='productno',
            field=models.CharField(max_length=100, verbose_name='商品序列码'),
        ),
    ]
